#!/usr/bin/env bash
# Host-side devcontainer initializeCommand.
#
# Makes the dev container work when the project is checked out as a git
# *worktree* (its `.git` is a file pointing at an absolute gitdir in the main
# checkout, which is not otherwise mounted). We generate a git-ignored compose
# override that bind-mounts the main repo's `.git` directory at the SAME
# absolute path inside the container, so the worktree's `gitdir:` pointer
# resolves with no rewriting of git internals.
#
# For a normal clone we emit a no-op override. Idempotent; safe to re-run.
# See wiki: patterns/devcontainer-worktree-git-mount.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$SCRIPT_DIR/docker-compose.worktree.yml"
TEMPLATE="$SCRIPT_DIR/docker-compose.worktree.yml.in"
GIT_PATH="$WS_DIR/.git"

if [ -f "$GIT_PATH" ]; then
  # Worktree: ".git" is a file "gitdir: <main>/.git/worktrees/<name>".
  gitdir="$(sed -n 's/^gitdir: //p' "$GIT_PATH")"
  if [ -z "$gitdir" ]; then
    echo "[init] .git is a file but has no gitdir: pointer; emitting no-op" >&2
    cp "$TEMPLATE" "$OUT"
    exit 0
  fi
  # Mount the main repo's top-level .git dir (two levels up from the
  # per-worktree gitdir) at its identical host path.
  main_git="$(cd "$(dirname "$gitdir")/.." && pwd)"
  cat > "$OUT" <<EOF
# GENERATED by .devcontainer/init.sh — do not edit, do not commit.
services:
  app:
    volumes:
      - ${main_git}:${main_git}:cached
EOF
  echo "[init] worktree detected; mounting ${main_git} at identity path"
else
  # Normal clone: .git is a self-contained directory already inside the mount.
  cp "$TEMPLATE" "$OUT"
  echo "[init] normal clone; no worktree git mount needed"
fi
